import Head from 'next/head'
import Link from 'next/link';
import React from 'react';
import styles from '@/styles/Home.module.css'
import PagesHeadComp from '@/complements/components/PagesHeadComp/PagesHeadComp'
import FooterComp from "@/complements/components/FooterComp/FooterComp";
import Image from 'next/image'


export default function Home() {
  return (
    <>
      <Head>
        <title>Appy.yo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#2F303A" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta httpEquiv='ScreenOrientation' content='autoRotate:disabled' />
        <link rel="icon" href="/Icons/manifest_icons/appyyo.png" />
      </Head>
      <PagesHeadComp
        data={{
            // faviconURL: "/Icons/manifest_icons/appyyo.png",
            faviconURL: "/Images/logo.png",
            title: "Appy.yo - Home",
            description: "",
            keywords: "",
        }}
      />
      <main className={styles.main}>
        <div className={styles.GetTouchCont}>
          <a href={'/GetInTouch'} className={styles.MenuButton}>Get In Touch</a>
        </div>
        <div id={styles.Logo}><Image src="/Images/logo.png" alt="Appy.yo Logo" fill/></div>
        <div id={styles.MainLinksMenu}>
          <Link  style={{textDecoration:'none'}} id={styles.AboutUs} className={styles.MainLink} href="/AboutUs"><span>About Us</span></Link>
          <Link  style={{textDecoration:'none'}} id={styles.InnovationLab} className={styles.MainLink} href="/InnovationLab"><span>Innovation Lab</span></Link>
          <Link  style={{textDecoration:'none'}} id={styles.NewestProject} className={styles.MainLink} href="/NewestProject"><span>Projects</span></Link>
          <Link  style={{textDecoration:'none'}} id={styles.ProfessionalServices} className={styles.MainLink} href="/ProfessionalServices"><span>Professional Services</span></Link>
          <Link  style={{textDecoration:'none'}} id={styles.DigitalTransformation} className={styles.MainLink} href="/DigitalTransformation"><span>Digital Transformation</span></Link>
        </div>
      </main>
      <FooterComp 
          classNames={''}
          langs={{
          developed: "Developed by",
          copyright: "Copyright",
          made: "made",
          version: "version",
          }}
          styles={{backgroundColor: 'rgb(43,44,56)'}}
      />
    </>
  )
}
