import React from "react";
import Image from "next/image";
import Head from "next/head";
import PagesHeadComp from "@/complements/components/PagesHeadComp/PagesHeadComp";
import FooterComp from "@/complements/components/FooterComp/FooterComp";
import styles from "@/styles/professionalServices.module.css"
import {HeaderCompBoots} from '@/complements/components/HeaderComp/HeaderCompBoots';

export default function ProfessionalServices(){

    return(
        <>
            <Head>
                <title>Professional Services</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/Icons/manifest_icons/appyyo.png" />
                <meta name="theme-color" content="#2F303A" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta httpEquiv='ScreenOrientation' content='autoRotate:disabled' />
            </Head>
            <PagesHeadComp
                data={{
                    faviconURL: "/Icons/manifest_icons/appyyo.png", //URL of icon to be displayed besides the title tab.
                    title: "Appy.yo® - Home", //Title to be displayed in the tab. In case of traslations needs to consider the marker and tag to be traslated, such as this sample.
                    description: "", //Description to be read by SEO for this page
                    keywords: "", //Keywords to be read by SEO for this page
                }}
            />
            <HeaderCompBoots />
            <main className={styles.main}>
                <article className={styles.article}>
                    <h1>Professional Services</h1>
                    <p>Do you need a special talent on your team only for a short period of time?</p>
                    <p>Are you struggling with an area and need improvement ?</p>
                    <p>Possibly you have bad reviews and you are not sure how to improve?</p>
                    <p>Professional services and process improvement is our niche.We are here to support you in your growth. Large companies struggle with the same issues - when they grow, a lot of processes need to be changed otherwise it results in bad quality, unhappy employees and even worst: bad reviews and public opinion.</p>
                    <p>Appy.yo team has expertise in reviewing your current setup and provides you with detailed advice by giving you a full understanding of where improvements can happen and how to tackle them.</p>
                    <p>Contact us to find out more about the talents we have or how to improve your processes</p>
                </article>
                <span className={styles.Image}>
                    <Image className={styles.Img} src="/Images/ProfesionalServices.jpeg" fill alt="Innovation_Lab"/>
                </span>
                <a href={'/GetInTouch'} className={styles.ServicesButton} id="ServNeeded">Describe the services you need</a>
            </main>
            {/*Footer Component*/}
            <FooterComp 
                classNames={''}
                langs={{
                developed: "Developed by",
                copyright: "Copyright",
                made: "made",
                version: "version",
                }}
            />
        </>
    )
}