import React from "react";
import Image from "next/image";
import Head from "next/head";
import PagesHeadComp from "@/complements/components/PagesHeadComp/PagesHeadComp";
import FooterComp from "@/complements/components/FooterComp/FooterComp";
import styles from '@/styles/project.module.css'
import {HeaderCompBoots} from '@/complements/components/HeaderComp/HeaderCompBoots';

export default function Project(){

    return (
        <>
            <Head>
                <title>Shopful Project</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/Icons/manifest_icons/appyyo.png" />
                <meta name="theme-color" content="#2F303A" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta httpEquiv='ScreenOrientation' content='autoRotate:disabled' />
            </Head>
            <PagesHeadComp
                data={{
                    faviconURL: "/Icons/manifest_icons/appyyo.png", //URL of icon to be displayed besides the title tab.
                    title: "Appy.yo® - Home", //Title to be displayed in the tab. In case of traslations needs to consider the marker and tag to be traslated, such as this sample.
                    description: "", //Description to be read by SEO for this page
                    keywords: "", //Keywords to be read by SEO for this page
                }}
            />
            <HeaderCompBoots />
            <main className={styles.main}>
                <article className={styles.article}>
                    <h1 className={styles.NewProj}>Shopful</h1>
                    <p>
                        Online shopping has given us access to worldwide products at competitive prices, malls are slowly phasing out. Have you ever realized last minute that you need to purchase something and you only have a few days or hours? Or maybe you still like to try on things but dont know which stores you should go to?
                    </p>
                    <p>
                        Shopful offers a quick way to find what you are looking for so that you can go directly to those stores. Need an outfit for tomorrows event but not sure where to look? Type in black jeans, choose your radius and there you go! Hit up all the stores that carry black jeans. Try them on and no more waiting and guessing when your package comes and chasing the courier!
                    </p>
                    <p>
                        Shopful gives you access to all the products in your radius for the last minute shoppers and the people who like to try it on!
                    </p>
                </article>
                <span className={styles.Image}>
                    <Image className={styles.Img} src="/Images/Shopful.jpg" fill alt="Poste"/>
                </span>
            </main>
            <FooterComp 
                classNames={''}
                langs={{
                developed: "Developed by",
                copyright: "Copyright",
                made: "made",
                version: "version",
                }}
            />
        </>
    )
}